### PR TITLE
formatted reponse module implemented

### PR DESCRIPTION
**Pull request by chrisjgilbert**
- created a formatted response module which takes api response and puts it into a formatted dictionary

### CODE REVIEW

**Comment by chrisjgilbert** [comment]
- results page now showing all emotional responses

**Comment by topickering** [comment]
Brilliant, great work! 🚯 
I particularly like the percentage rounding...

**Comment by jamesdew12** [comment]
🚯

**Comment by kirillzabrodin** [comment]
This looks beautiful! 🚯

**Pull request merged**
