### PR TITLE
Heroku

### PR DESCRIPTION
**Pull request by kirillzabrodin**
- Fixed all Heroku and Travis issues
- Hidden secret key

### CODE REVIEW

**Comment by kirillzabrodin** [comment]
🚯 ?

**Comment by kirillzabrodin** [comment]
Failing to deploy on Heroku because it just did already. Should work on master.

**Comment by chrisjgilbert** [comment]
superb work
🚯

**Comment by topickering** [comment]
I've seen it with my own eyes, so 🚯

**Pull request merged**
