### PR TITLE
Tp holmes

### PR DESCRIPTION
**Pull request by topickering**
Holmes analyser and Holmes classifier added and tested (with mocks)

### CODE REVIEW

**Comment by topickering** [comment]
All tests passed... 🚯 ?

**Comment by kirillzabrodin** [comment]
Nicely done! 🚯 Will merge tomorrow after someone else has a look as well!

**Comment by kirillzabrodin** [comment]
🚯 Looking great Tom! Well done you bearded angel!

**Comment by chrisjgilbert** [comment]
🚯

**Pull request merged**
