### PR TITLE
Bootstap

### PR DESCRIPTION
**Pull request by chrisjgilbert**
- improved homepage styling and added form for future twitter feature

### CODE REVIEW

**Comment by chrisjgilbert** [comment]
- merge conflict resolved

**Comment by topickering** [comment]
I'm trying not to be too distraught that you're front-end looks so much better than mine!
🚯

**Comment by topickering** [comment]
Or that I wrote 'you're' rather than 'your', which is unforgivable.

**Comment by chrisjgilbert** [comment]
🚳

**Comment by kirillzabrodin** [comment]
🚯

**Pull request merged**
